language: python

python:
  - 3.7

install:
  - pip install -r requirements_test.txt
  - pip install tox-travis

script:
  - tox

cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
  - master

after_success:
  - python -m codecov
